name: CI

on:
  push:
    branches: [main, uat, stage, "feature/**"]
  pull_request:
    branches: [main, uat, stage]

jobs:
  basic-ci:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::460783431820:role/GitHubActionsCIRole
          aws-region: ap-south-1
          role-session-name: github-actions-ci

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run test suite
        env:
          NODE_ENV: test
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DB_NAME: aws_serverless
          TEST_DB_NAME: aws_serverless_test
        run: npm test
      
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 --provenance=false -t aws-serverless-project:ci .

      - name: Check Terraform formatting
        run: terraform -chdir=terraform fmt -check -recursive
      
      - name: Initialize Terraform
        run: terraform -chdir=terraform init -backend=false

      - name: Validate Terraform
        run: terraform -chdir=terraform validate

      - name: CI completed
        run: echo "CI job completed successfully."



